# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

install:
  - ./install.sh true

language: generic

matrix:
  include:

    - os: osx
      osx_image: xcode9.2

notifications:
  email:
    on_failure: always
    on_success: never

sudo: required
